### ISSUE TITLE
replace date at task config

### ISSUE THREAD

**Issue by sawadashota** [crowdworks/slacts#23]
AsIs
---

hard writing date configuration

```yaml
tasks:
  - name: "test_task"
    kind: "count"
    query: "in:#general on:2018/12/03"
```

ToBe
---

replace value like this

```yaml
tasks:
  - name: "test_task"
    kind: "count"
    query: "in:#general on:{{ .Yesterday }}"
```
